apiVersion: v1
kind: Service
metadata:
  labels:
    name: sre-ebs-iops-reporter
  name: sre-ebs-iops-reporter
  namespace: openshift-monitoring
spec:
  ports:
  - name: http-main
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    name: sre-ebs-iops-reporter
  sessionAffinity: None
  type: ClusterIP
