---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dedicated-admin-operator
  namespace: openshift-dedicated-admin
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  attributeRestrictions: null
  resources:
  - rolebindings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch