apiVersion: v1
kind: Service
metadata:
  name: dedicated-admin-operator
  namespace: openshift-dedicated-admin
  labels:
    k8s-app: dedicated-admin-operator 
spec:
  ports:
  - name: metrics
    port: 8080
  selector:
    k8s-app: dedicated-admin-operator
  type: ClusterIP