apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
      k8s-app: dedicated-admin-operator
  name: dedicated-admin-operator
  namespace: openshift-dedicated-admin
spec:
  endpoints:
  - port: metrics
    scheme: http
    interval: 30s
  selector:
    matchLabels:
      k8s-app: dedicated-admin-operator

